---
- include_vars:
  file: group_vars/guests.yml

- hosts: server02
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - reset_interfaces
    - install_kvm
    - install_ovs
    - build_vms
