---
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown2
    - quagga
- hosts: spines
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown2
    - quagga
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown
- hosts: server01
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - iperf-client
- hosts: server02
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - iperf-server
