# Install bmon for watching the traffic & iperf for generating it

- name: Install iperf
  apt: name=iperf update_cache=yes

- name: Install bmon
  apt: name=bmon update_cache=yes

- name: Install ruby
  apt: name=ruby update_cache=yes

- name: Install tmuxinator
  gem: name=tmuxinator

- name: Setup tmuxinator environment
  template: src=/templates/iperf.yml dst=~/.tmuxinator/iperf.yml owner=cumulus

- name: Start tmuxinator
  command: tmuxinator start iperf
  become: true
  become_user: cumulus
  become_method: sudo
