# Install and configure OVS for interface eth2 on server02

- name: Install KVM
  apt: name={{ item }} update_cache=yes
  with_items:
    - qemu-kvm
    - libvirt-bin
    - ubuntu-vm-builder
    - bridge-utils
    - virtinst

- name: Add user cumulus to libvirtd and kvm group
  command: "{{ item }}"
  with_items:
    - adduser cumulus libvirtd
    - adduser cumulus kvm
  become: true
  become_user: root
  become_method: sudo

- name: apt-get dist-upgrade -qy
  apt: upgrade=dist
