# Install tmuxinator and connect to the various servers in the environment

- name: Install ruby
  apt: name=ruby update_cache=yes

- name: Install tmuxinator
  command: gem install tmuxinator
  become: true
  become_user: root
  become_method: sudo

- name: Ensure tmuxinator folder
  file: path=~/.tmuxinator/ state=directory
  become: true
  become_user: cumulus
  become_method: sudo

- name: Get a list of tmuxinator files
  action: command ls -1 roles/oob-mgmt-server/templates/*.yml
  register: tmuxfiles

- name: Setup tmuxinator environment
  template: src=$item dest=~/.tmuxinator/ owner=cumulus
  become: true
  become_user: cumulus
  become_method: sudo
  with_items: ${tmuxfiles.stdout_lines}
